### ISSUE TITLE
ImportError : Cannot import name 'Window'

### ISSUE THREAD

**Issue by ghost** [44yu5h/rpi_control_center#6]
```
File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 179, in main module = _import_(module_name)
File "/home/pi/Activities/rpi_control_center/activity.py", line 6, 
import rp_tests.rp_gpio as rp_gpio
File "/home/pi/Activities/rpi_control_center/rp_tests/rp_gpio.py", line 12, in <module>
from utils import Window, load_css
ImportError: cannot import name 'Window' from 'utils' 
```

On using git bisect this error came in at this commit a4b6383c4f7f6ccb55d8b82a29cfabdb57ec76cf
@44yu5h  @chimosky 
Before that everything working fine as planned.

**Comment by 44yu5h** [comment]
It was an error on my end. I thought I tested it but I didn't
T&R

**Comment by ghost** [comment]
Thanks!!
